### ISSUE TITLE
enable the "send a massage to.." option for the cosmetician

### ISSUE THREAD

**Issue by TamarKl** [Rut-B/TM-COSMETICS#25]
#### This task is done when:
- [ ] The cosmetician can choose the option of sending a message.
- [ ] The cosmetician can then choose from the options who will she send the msg to... (specific customers or groups)
- [ ]  The cosmetician can write the message.
- [ ] The message is sent to the customers.

**Comment by Rut-B** [comment]
is open

**Comment by Rut-B** [comment]
there is no time,
